# Generated by Django 3.0.7 on 2020-06-26 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Real_Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Timezone', models.CharField(max_length=100, verbose_name='Timezone')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.CharField(max_length=100, verbose_name='StartTime')),
                ('End_Time', models.CharField(max_length=100, verbose_name='EndTime')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.User')),
            ],
        ),
    ]
